  spring:
    application:
      name: dryforest_app

    datasource:
      url: jdbc:postgresql://localhost:5432/dryforest_app # # jdbc:postgresql://dpg-d8gm4etckfvc73cs6q8g-a.frankfurt-postgres.render.com:5432/dryforest?ssl=true&sslmode=require
      username: postgres
      password: florentino # y4lTdfLMrP3X9Hs6qtsHZYScOwq03LdC
      driver-class-name: org.postgresql.Driver

    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

    sql:
      init:
        mode: never # always
        separator: "@@"
        schema-locations:
          - classpath:data.sql
          - classpath:views.sql

    flyway:
      enabled: false

  server:
    port: 8081

  sync:
    pullable-tables:
      patrol:
        - patrol_groups
        - incident_types
        - observation_types
        - categories
        - animals

      reforestation:
        - persons
        - species_types
        - species
        - severities
        - zone_types
        - patrol_groups
        - categories
        - animals
  app:
    property:
      max-age: 3600
      header-type: Bearer
      frontend-domain: http://localhost:5271
      jwt-signing-key: "Biy3xH6+WY6asNSSngRdyHNnV+dSl0l62ZU1+9DLfESLVdquHelviFT0Gc1nDnu/yJDt9fA6pZRvcWb701gfc00dyDt9Ueb2ATTkqL+GNms="
      jwt-expiration-date: 7776000000